spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://scrap-kepco-table.clkbkeebupel.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl # 자동 camelCase-> underscore 전환 방지.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        check_nullability: true
        validator:
          apply_to_ddl: true
        format_sql: true
        show_sql: true
  jackson:
    default-property-inclusion: non_null

